version: "3.8"

services:
  app:
    image: node:18 # or whichever Node.js version you're using
    container_name: node_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start" # Replace "npm run start" with your actual start script if different
    ports:
      - "3000:3000" # Map the internal port to your preferred external port
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development # or production as needed
    build:
      context: .
      dockerfile: Dockerfile

  mongo:
    image: mongo:5.0 # Specify the MongoDB version you want
    container_name: mongo_db
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=test1234 # Update these credentials as per your requirement

volumes:
  mongo_data:
    driver: local
